#!/usr/bin/env node
/**
 * sync-status.js
 * Reads PRD files in ~/PRDs/, extracts status percentages,
 * writes data/status.json, then auto-commits + pushes.
 *
 * Usage:  npm run sync-status
 * Or:     node scripts/sync-status.js [--dry-run]
 */

const fs   = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const DRY_RUN = process.argv.includes('--dry-run');
const PRD_DIR = path.join(process.env.HOME, 'PRDs');
const OUT     = path.join(__dirname, '../data/status.json');

// Map PRD filename → status.json key
const PRD_MAP = {
  'kura.md':          'kura',
  'lemari.md':        'wardrobify',
  'radius-flight.md': 'radius',
  'colokkan.md':      'colokkan',
};

// Regex: matches "**Status:** 🚀 95% Complete" or similar
const STATUS_RE = /\*\*Status:\*\*[^0-9]*(\d+)%/;

// ── Parse PRDs ──────────────────────────────────────────────────────
const result = {};

for (const [file, key] of Object.entries(PRD_MAP)) {
  const full = path.join(PRD_DIR, file);
  try {
    const content = fs.readFileSync(full, 'utf8');
    const match   = content.match(STATUS_RE);
    if (match) {
      result[key] = parseInt(match[1], 10);
      console.log(`  ✓ ${file} → ${key}: ${result[key]}%`);
    } else {
      console.warn(`  ⚠ ${file}: no status line found`);
    }
  } catch {
    console.warn(`  ✗ ${file}: not found at ${full}`);
  }
}

// Challenge weeks shipped (12/52 ≈ 23%) — update this manually when you ship a new week
result.challenge = 23;

result._updated = new Date().toISOString();
result._note    = 'Auto-generated by scripts/sync-status.js — do not edit manually';

// ── Compare with existing ───────────────────────────────────────────
let changed = false;
try {
  const existing = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  const keys = [...Object.values(PRD_MAP), 'challenge'];
  changed = keys.some(k => existing[k] !== result[k]);
} catch {
  changed = true;
}

if (!changed) {
  console.log('\nNo status changes detected. Nothing to commit.');
  process.exit(0);
}

// ── Write JSON ─────────────────────────────────────────────────────
if (DRY_RUN) {
  console.log('\n[dry-run] Would write:', JSON.stringify(result, null, 2));
  process.exit(0);
}

fs.writeFileSync(OUT, JSON.stringify(result, null, 2) + '\n');
console.log('\nWrote data/status.json');

// ── Commit + Push ──────────────────────────────────────────────────
// execFileSync avoids shell injection — all args are literal strings
const repoRoot = path.join(__dirname, '..');
const git = (args) => execFileSync('git', args, { cwd: repoRoot, stdio: 'inherit' });

try {
  git(['add', 'data/status.json']);
  git(['commit', '-m', `chore: sync project status [${new Date().toISOString().slice(0, 10)}]`]);
  git(['push']);
  console.log('\n✅ Pushed. Vercel will redeploy automatically.');
} catch (err) {
  console.error('\nGit error — run manually if needed:', err.message);
  process.exit(1);
}
